server:
  port: 9002
spring:
  application:
    name: cloud-nacos
  cloud:
    nacos:
      serverAddr: 192.168.80.129:1111
  config:
    import:
      - nacos:nacos-config-example.properties?refresh=true
#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
