server:
  port: 8001

spring:
  application:
    name: cloud-payment-hystrix-8001
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效

eureka:
  instance:
    instance-id: payment-service-8001 #自定义服务名称信息
    prefer-ip-address: true
  client:
    register-with-eureka: true #false表示不向注册中心注册自己。
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka