server:
  port: 8004

spring:
  application:
    name: cloud-payment-8004
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  cloud:
    zookeeper:
      connect-string: 192.168.80.129:2181