server:
  port: 8802
spring:
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        ## 新版本固定格式  channel名字-{out/in}-{index}
        linkChannel-in-0:  #自定义管道名称
          destination: studyExchange  #自定义Exchange名称
          contentType: application/json
          group: group1
    function:
      definition: linkChannel
  application:
    name: cloud-stream-client
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true #false表示不向注册中心注册自己。
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"