server:
  port: 9527

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #配置动态路由，根据微服务名路由
      routes:
        - id: after_route
          uri: lb://CLOUD-PAYMENT-SERVICE	#匹配后提供服务的路由地址
          predicates:
            - Path=/payment/getPayment/**	#断言，路径匹配后进入路由

        - id: after_route2
          uri: lb://CLOUD-PAYMENT-SERVICE    #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/getPayment/**    #断言，路径匹配后进入路由
  application:
    name: cloud-gateway

eureka:
  instance:
    instance-id: gateway-9527 #自定义服务名称信息
    prefer-ip-address: true
  client:
    register-with-eureka: true #false表示不向注册中心注册自己。
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka