server:
  port: 80

spring:
  application:
    name: cloud-payment-consumer
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
      freemarker:
        cache: false    #页面不加载缓存，修改即时生效

eureka:
  instance:
    instance-id: consumer-service-80 #自定义服务名称信息
    prefer-ip-address: true
  client:
    register-with-eureka: true #false表示不向注册中心注册自己。
    fetch-registry: true #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka